### ISSUE TITLE
Supply a separate menu for use with subsites by default.

### ISSUE THREAD

**Issue by rupertj** [localgovdrupal/localgov_subsites_extras#1]
While you can use any menu, it'd be nice if we supplied one for people to use.
- [ ] Add a menu by default when the module's installed.
- [ ] Ensure that existing content types can be added to it.
- [ ] Ensure that new content types can be added to it.

**Comment by markconroy** [comment]
Related issue: https://github.com/localgovdrupal/localgov_base/issues/526

**Comment by rupertj** [comment]
Closing this as we have a menu set up now. We still need to place the menu block for it automatically, but that should be a separate issue, I think.
