### ISSUE TITLE
Can't add a <nolink> menu item

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_subsites_extras#20]
When adding a `<nolink>` menu item to the subsites menu, the subsites menu causes a WSOD.
> TypeError: Drupal\localgov_subsites_extras\Service\SubsiteService::walkMenuTree(): Argument 1 ($node) must be of type Drupal\node\NodeInterface, null given, called in /app/web/modules/contrib/localgov_subsites_extras/src/Service/SubsiteService.php on line 102 in Drupal\localgov_subsites_extras\Service\SubsiteService->walkMenuTree() (line 88 of modules/contrib/localgov_subsites_extras/src/Service/SubsiteService.php).

What should happen:
Menu displays with the nolink option

**Comment by andybroomfield** [comment]
It's to do with the way this module tries to discover the subsite homepage.
https://github.com/localgovdrupal/localgov_subsites_extras/blob/2b61f1ef6d073196bdaf6feeafc0a0b0e4e2f46f/src/Service/SubsiteService.php#L85-L106

We can't assume a menu link will always be a node, It could also be a view, custom controller, form, external or `<nolink>` which is a common way of adding menu sections. Instead we should try to use the menu link and check if it's a node, and if not, continue up to the next level.

**Comment by rupertj** [comment]
I'm pretty sure that https://github.com/localgovdrupal/localgov_subsites_extras/pull/16 will fix this.

**Comment by rupertj** [comment]
Having come back to this after that other issue is resolved, it'll stop the WSOD, but it won't let the search for a subsite homepage continue up the tree past a menu link that doesn't link to a node.

Re-doing the method that walks the tree as per your suggestion sounds sensible @andybroomfield.

**Comment by rupertj** [comment]
@andybroomfield I've re-implemented the code to find the subsite homepage as suggested. Care to give it a try?

**Comment by rupertj** [comment]
Closing this as the PR's merged. @andybroomfield I think the issue here's resolved, but please do re-open it if I'm mistaken. Thanks!
