### ISSUE TITLE
Collapseable / Flyout menus

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_subsites_extras#21]
Is it possible to build collapsible / flyout menus with this module?
Where we would have several section that extend out with child items. Is this something that needs to be themed?

**Comment by markconroy** [comment]
Hi @andybroomfield 

This is not possible for iteration 1 of the feature. Currently we are only supporting single-level menus. 

Let's leave this open and see if we can support multi-level menus during a later phase of work (it's probably not too difficult).

===
Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

**Comment by rupertj** [comment]
Well, it's kind of possible. This module doesn't do anything with menus other than place a menu block with the right configuration to show up for subsites. There's nothing we do that'll prevent the use of multi-level menus or collapsible menus that I can think of.

Closing as I think the question's answered. If there does turn out to be something this module does that does stop anything like that working, please file a new issue - I'd be happy to look at a fix for it.
