### ISSUE TITLE
Subsites cache context

### ISSUE THREAD

**Issue by Polynya** [localgovdrupal/localgov_subsites_extras#24]
Add cache context for subsites, for example, so that blocks can be cached separately for the main website and a subsite:

```
/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 */
function example_block_view_system_branding_block_alter(array &$build, BlockPluginInterface $block) {
  $build['#cache']['contexts'][] = 'subsites';
}
```

**Comment by Polynya** [comment]
https://github.com/localgovdrupal/localgov_subsites_extras/pull/23

**Comment by markconroy** [comment]
The attached PR is merged, so closing this issue.
