### ISSUE TITLE
subsites extas should have a requirement for subsites

### ISSUE THREAD

**Issue by markconroy** [localgovdrupal/localgov_subsites_extras#25]
At the moment it's possible to install Subsites Extras module on its own, without the subsites module. But then it will do nothing. 

It should have subsites as a dependency.

**Comment by rupertj** [comment]
This is a won't fix for me, as you don't actually need subsites to use subsites_extras.

**Comment by markconroy** [comment]
Mind ... blown ... 🤯 

Thanks Ru!

**Comment by rupertj** [comment]
To explain this better :)

subsites_extras needs a content type to be the subsite, but beyond that it doesn't need anything else to work. You can use it  with the types provided by subsites, or you can use it with your own content types, which is how H&F is set up. H&F don't even have subsites turned on, and I'm planning to remove the module and its dependencies entirely at some point.

You could go totally off the wall and have the service landing page as your subsite type and give each service its own colour scheme if you wanted to...

**Comment by markconroy** [comment]
This sounds like it might make a nice generic module for Drupal.org rather than just for LGD.

Well done.
