### ISSUE TITLE
Change name to localgov_subsites_menu ?

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_subsites_extras#8]
This is a followup to #7.

I think the confusion might also be the generic name, could we consider naming this to be more reflective of its function (it's just the extra pages via a menu that added here?)

This might be better suited as a sub module in the long term, maybe the canioncal way of adding subsite pages in a version 3.x of subsites?

**Comment by markconroy** [comment]
I'd like to keep the name generic rather than saying it's only for menus. Given it's adding classes to the body, there's so much more we can do with these pages than just style a menu. Those body classes can be used to affect all parts of the page, via CSS and/or JS.

**Comment by rupertj** [comment]
I initially named this module [localgov_menu_subsites](https://github.com/wearechicken/localgov_menu_subsites) but in one of the initial meetings, we came to the conclusion that it wasn't a good name, and localgov_subsites_extras would be better.

I think it makes sense to stick with what it is, with the same reasoning as Mark.

It wouldn't surprise me if this module merges with localgov_subsites in some way in the future. It's actually possible to set up "Subsites" using just this module and not localgov_subsites right now - that's how H&F's site works.
